# Generated by Django 5.0 on 2024-01-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
