# Generated by Django 5.0 on 2024-01-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_template_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
