# Generated by Django 5.0 on 2024-01-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_template_username_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailConfirmed',
            field=models.BooleanField(default=False),
        ),
    ]
